### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by KarelWintersky** [Salsabanana/ARK_Starmap#1]
How to 'run' this map? 

Linux / windows

**Comment by Synchrones** [comment]
Hi, you can download the .exe installer in the release tab, it will install the starmap on your computer and you should be abble to launch it like any other app...
I think it only work on windows, i'll need to create specifics installers for them to work on mac/linux

**Comment by KarelWintersky** [comment]
I'll try, thank you.

**Comment by KarelWintersky** [comment]
Fatal error: "Failed to load mono"

**Comment by Synchrones** [comment]
Hum... I assume you didn't get any more info on the error... When did you get it? When installing? It could be caused by a lot of things, maybe it's missing permissions so you could try running as admin but I don't think it will fix it...

**Comment by KarelWintersky** [comment]
After installing I lauched application and got this error. 

Launched by admin, of course

**Comment by Synchrones** [comment]
Do yo see something with your pc that could cause a problem? Like is it old, is it on a old windows version/a windows virtual machine? 
You can also try installing an older release to see if you get the same error.

**Comment by KarelWintersky** [comment]
Windows 10, build 1809 LTSC Corporate

> You can also try installing an older release to see if you get the same error.

Same error
![изображение](https://user-images.githubusercontent.com/2164874/181599750-1ce0313d-512e-4c6c-9596-d8160ddaf6b2.png)

**Comment by KarelWintersky** [comment]
There is no mono.dll 

Can you write, how to build EXE from sources?

**Comment by Synchrones** [comment]
That's a kinda strange issue... 
So, to build it from source you would need to install the unity editor and then import the project to be able to build it.
To simplify the process, I just added a buid of the current version to the last release's files, you can just download the .zip, it should contain a working version of the app.

**Comment by Synchrones** [comment]
Okay, I found the issue! It was just a missing sub dir that I forgot since the last two update but as I was installing it above the first version that was correctly made, it was only overwriting the content dir and I didn't got the error.
I'm going to update the installers, it should be done very soon.

**Comment by Synchrones** [comment]
Should be working now, I also added a section in the readme with the controls as some of them aren't that intuitive...

**Comment by KarelWintersky** [comment]
Oh my god, it's beautiful.

How I can build my own Universe world map? I have 2d projection ( https://livemap.wintersky.ru/map/spring.confederation ), but want make 3d :)

**Comment by Synchrones** [comment]
Glad to see you like it!
So if you wanted something like this, you could create a 3D unity project and use the datas from the 2D projection to procedurally generate the stars, from what I can see the datas are in the file that I attached on this comment, you should be abble to parse it in some way... You will still need to create a camera system and you will be missing the Z coordinate of the stars as your projection is in 2D.
[spring.confederation.txt](https://github.com/Salsabanana/ARK_Starmap/files/9220470/spring.confederation.txt)

**Comment by KarelWintersky** [comment]
I'll try...
